version: "3.3"
services:
  mongodb_container:
    image : mongo:latest
    container_name: professional_assessment
    volumes:
      - ./mongo/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped